function jacobian = equil_variational_general_jacobian(L,LX,x,cache)
%EQUIL_VARIATIONAL_GENERAL_JACOBIAN Exact P_parallel(r,R,B) tangent.
%   The local magnetic-field equation is differentiated implicitly and
%   condensed pointwise.  A complete trial-profile block is represented by
%   two two-dimensional coefficient fields multiplying its radial value
%   and derivative matrices, respectively.  Angular averaging therefore
%   precedes radial projection and no quadrature-by-angle-by-coefficient
%   tangent array is formed.

    if nargin < 4
        cache = [];
    end

    if isempty(cache) || ~isfield(cache,'local')
        [~,cache] = equil_variational_residual(L,LX,x,[]);
    end

    state = cache.state;
    local = cache.local;
    edge_local = cache.fields.edge;
    require_general_pressure_derivatives(local.pressure);
    require_general_pressure_derivatives(edge_local.pressure);

    epsilon = state.epsilon;
    nprofiles = 3+L.P.Ns+L.P.Na+double(L.P.vertical_shift);
    jacobian = spalloc(L.total_dofs,L.total_dofs,L.total_dofs^2);

    [coeff_J,~,coeff_goo] = ...
        anisotropic_coefficients(state,local);
    [edge_coeff_J,~,~] = ...
        anisotropic_coefficients(state.edge,edge_local);

    one_minus_sigma = 1-local.sigma;
    flux_source = local.pressure.Pr+state.T.*state.Tr./( ...
        state.R.^2.*one_minus_sigma);
    flux_prefactor = state.J./(epsilon*state.psir);

    for trial_profile = 1:nprofiles
        columns = block_rows(L,trial_profile);
        direction = profile_direction(L,trial_profile,epsilon,state.omega);
        edge_direction = profile_direction( ...
            L,trial_profile,epsilon,state.edge.omega);
        tangent = kinematic_coefficients(state,direction);
        edge_tangent = kinematic_coefficients(state.edge,edge_direction);
        condensed = local_B_tangent(state,direction,tangent,local);
        edge_condensed = local_B_tangent( ...
            state.edge,edge_direction,edge_tangent,edge_local);

        % Flux-equation row block.  P_parallel,r remains the partial
        % derivative at fixed (R,B), while its Newton tangent contains
        % PrR*dot(R)+PrB*dot(B).
        dflux_derivative = flux_derivative_tangent( ...
            state,tangent,condensed,local);
        dflux_prefactor.v = tangent.Jv./(epsilon*state.psir) ...
            -state.J.*tangent.psirv./(epsilon*state.psir.^2);
        dflux_prefactor.d = tangent.Jd./(epsilon*state.psir);
        dflux_source = flux_source_tangent( ...
            state,direction,condensed,local);
        dflux_value.v = flux_source.*dflux_prefactor.v ...
            +flux_prefactor.*dflux_source.v;
        dflux_value.d = flux_source.*dflux_prefactor.d ...
            +flux_prefactor.*dflux_source.d;
        edge_dflux = flux_derivative_tangent( ...
            state.edge,edge_tangent,edge_condensed,edge_local);
        rows = block_rows(L,1);
        jacobian(rows,columns) = ( ...
            project_linear(L,1,dflux_derivative,trial_profile,true) ...
            -project_linear(L,1,dflux_value,trial_profile,false) ...
            -project_edge_linear(L,1,edge_dflux,trial_profile))/epsilon^2;

        % Exact anisotropic SFL periodicity constraint.  sigma_cyl(r) is
        % prescribed during the global Newton solve.
        dgauge.v = tangent.Jv./(state.R.^2.*one_minus_sigma) ...
            -2*state.J.*direction.Rv./( ...
                state.R.^3.*one_minus_sigma) ...
            +state.J.*condensed.sigmav./( ...
                state.R.^2.*one_minus_sigma.^2);
        dgauge.d = tangent.Jd./(state.R.^2.*one_minus_sigma) ...
            +state.J.*condensed.sigmad./( ...
                state.R.^2.*one_minus_sigma.^2);
        rows = block_rows(L,3);
        jacobian(rows,columns) = ...
            project_linear(L,3,dgauge,trial_profile,false)/epsilon^3;

        [dcoeff_J,dcoeff_R,dcoeff_goo] = coefficient_tangents( ...
            state,direction,tangent,condensed,local);
        [edge_dcoeff_J,~,~] = coefficient_tangents( ...
            state.edge,edge_direction,edge_tangent, ...
            edge_condensed,edge_local);

        % Delta test block, including its natural edge term.
        test_J_value = -state.JoverR;
        test_J_derivative = -state.R.*state.Zw;
        dtest_J_value.v = -tangent.Hv;
        dtest_J_value.d = -tangent.Hd;
        dtest_J_derivative.v = -( ...
            state.Zw.*direction.Rv+state.R.*direction.Zwv);
        dtest_J_derivative.d = zeros(size(state.R));
        dvalue = product_rule(test_J_value,dcoeff_J, ...
            coeff_J,dtest_J_value);
        dvalue.v = dvalue.v-dcoeff_R.v;
        dvalue.d = dvalue.d-dcoeff_R.d;
        dderivative = product_rule(test_J_derivative,dcoeff_J, ...
            coeff_J,dtest_J_derivative);

        edge_test_J_derivative = -state.edge.R.*state.edge.Zw;
        edge_dtest_J_derivative.v = -( ...
            state.edge.Zw.*edge_direction.Rv ...
            +state.edge.R.*edge_direction.Zwv);
        edge_dtest_J_derivative.d = zeros(size(state.edge.R));
        edge_dderivative = product_rule(edge_test_J_derivative, ...
            edge_dcoeff_J,edge_coeff_J,edge_dtest_J_derivative);
        rows = block_rows(L,2);
        jacobian(rows,columns) = ( ...
            project_linear(L,2,dvalue,trial_profile,false) ...
            +project_linear(L,2,dderivative,trial_profile,true) ...
            -project_edge_linear(L,2,edge_dderivative,trial_profile)) ...
            /epsilon^4;

        % Symmetric shape test blocks.
        for is = 1:L.P.Ns
            n = is;
            cn = cos(n*state.omega);
            sn = sin(n*state.omega);
            radial_part = -n*state.Rr.*cn+n*state.Zr.*sn;
            test_J_value = state.JoverR.*cn+state.R.*radial_part;
            test_J_derivative = state.R.*(state.Zw.*cn+state.Rw.*sn);
            test_goo_value = -2*n*(state.Rw.*sn+state.Zw.*cn);

            dtest_J_value.v = tangent.Hv.*cn ...
                +direction.Rv.*radial_part;
            dtest_J_value.d = tangent.Hd.*cn+state.R.*( ...
                -n*direction.Rv.*cn+n*direction.Zv.*sn);
            dtest_J_derivative.v = direction.Rv.*( ...
                state.Zw.*cn+state.Rw.*sn)+state.R.*( ...
                direction.Zwv.*cn+direction.Rwv.*sn);
            dtest_J_derivative.d = zeros(size(state.R));
            dtest_goo_value.v = -2*n*( ...
                direction.Rwv.*sn+direction.Zwv.*cn);
            dtest_goo_value.d = zeros(size(state.R));

            dvalue = product_rule(test_J_value,dcoeff_J, ...
                coeff_J,dtest_J_value);
            dvalue.v = dvalue.v+cn.*dcoeff_R.v ...
                +test_goo_value.*dcoeff_goo.v ...
                +coeff_goo.*dtest_goo_value.v;
            dvalue.d = dvalue.d+cn.*dcoeff_R.d ...
                +test_goo_value.*dcoeff_goo.d;
            dderivative = product_rule(test_J_derivative,dcoeff_J, ...
                coeff_J,dtest_J_derivative);
            profile = 3+is;
            rows = block_rows(L,profile);
            jacobian(rows,columns) = ( ...
                project_linear(L,profile,dvalue,trial_profile,false) ...
                +project_linear(L,profile,dderivative, ...
                    trial_profile,true))/epsilon^4;
        end

        % Up-down asymmetric shape test blocks.
        for ia = 1:L.P.Na
            n = L.P.A_modes(ia)-1;
            cn = cos(n*state.omega);
            sn = sin(n*state.omega);
            radial_part = -n*state.Rr.*sn-n*state.Zr.*cn;
            test_J_value = state.JoverR.*sn+state.R.*radial_part;
            test_J_derivative = state.R.*(state.Zw.*sn-state.Rw.*cn);
            test_goo_value = 2*n*(state.Rw.*cn-state.Zw.*sn);

            dtest_J_value.v = tangent.Hv.*sn ...
                +direction.Rv.*radial_part;
            dtest_J_value.d = tangent.Hd.*sn+state.R.*( ...
                -n*direction.Rv.*sn-n*direction.Zv.*cn);
            dtest_J_derivative.v = direction.Rv.*( ...
                state.Zw.*sn-state.Rw.*cn)+state.R.*( ...
                direction.Zwv.*sn-direction.Rwv.*cn);
            dtest_J_derivative.d = zeros(size(state.R));
            dtest_goo_value.v = 2*n*( ...
                direction.Rwv.*cn-direction.Zwv.*sn);
            dtest_goo_value.d = zeros(size(state.R));

            dvalue = product_rule(test_J_value,dcoeff_J, ...
                coeff_J,dtest_J_value);
            dvalue.v = dvalue.v+sn.*dcoeff_R.v ...
                +test_goo_value.*dcoeff_goo.v ...
                +coeff_goo.*dtest_goo_value.v;
            dvalue.d = dvalue.d+sn.*dcoeff_R.d ...
                +test_goo_value.*dcoeff_goo.d;
            dderivative = product_rule(test_J_derivative,dcoeff_J, ...
                coeff_J,dtest_J_derivative);
            profile = 3+L.P.Ns+ia;
            rows = block_rows(L,profile);
            jacobian(rows,columns) = ( ...
                project_linear(L,profile,dvalue,trial_profile,false) ...
                +project_linear(L,profile,dderivative, ...
                    trial_profile,true))/epsilon^4;
        end

        if L.P.vertical_shift
            profile = 4+L.P.Ns+L.P.Na;
            test_J_derivative = -state.R.*state.Rw;
            dtest_J_derivative.v = -( ...
                direction.Rv.*state.Rw+state.R.*direction.Rwv);
            dtest_J_derivative.d = zeros(size(state.R));
            dderivative = product_rule(test_J_derivative,dcoeff_J, ...
                coeff_J,dtest_J_derivative);
            rows = block_rows(L,profile);
            jacobian(rows,columns) = project_linear( ...
                L,profile,dderivative,trial_profile,true)/epsilon^4;
        end
    end
end

function require_general_pressure_derivatives(pressure)
    required = {'Pi','Pr','PR','PB','PBB','PrB','PRB','PrR','PRR'};
    for k = 1:numel(required)
        if ~isfield(pressure,required{k})
            error(['The analytical variational pressure interface ', ...
                'requires field %s.'],required{k});
        end
    end
end

function direction = profile_direction(L,profile,epsilon,omega)
    zero = zeros(size(omega));
    direction.Tv = zero;
    direction.Rv = zero;
    direction.Zv = zero;
    direction.Rwv = zero;
    direction.Zwv = zero;

    if profile == 1
        direction.Tv = epsilon^2+zero;
    elseif profile == 2
        direction.Rv = -epsilon^2+zero;
    elseif profile == 3
        direction.Rv = epsilon^3*cos(omega);
        direction.Zv = epsilon^3*sin(omega);
        direction.Rwv = -epsilon^3*sin(omega);
        direction.Zwv = epsilon^3*cos(omega);
    elseif profile <= 3+L.P.Ns
        n = profile-3;
        direction.Rv = epsilon^2*cos(n*omega);
        direction.Zv = -epsilon^2*sin(n*omega);
        direction.Rwv = -epsilon^2*n*sin(n*omega);
        direction.Zwv = -epsilon^2*n*cos(n*omega);
    elseif profile <= 3+L.P.Ns+L.P.Na
        ia = profile-(3+L.P.Ns);
        n = L.P.A_modes(ia)-1;
        direction.Rv = epsilon^2*sin(n*omega);
        direction.Zv = epsilon^2*cos(n*omega);
        direction.Rwv = epsilon^2*n*cos(n*omega);
        direction.Zwv = -epsilon^2*n*sin(n*omega);
    else
        direction.Zv = epsilon^2+zero;
    end
end

function tangent = kinematic_coefficients(state,direction)
    tangent.Hv = state.Rr.*direction.Zwv ...
        -state.Zr.*direction.Rwv;
    tangent.Hd = state.Zw.*direction.Rv ...
        -state.Rw.*direction.Zv;
    tangent.Jv = state.JoverR.*direction.Rv+state.R.*tangent.Hv;
    tangent.Jd = state.R.*tangent.Hd;
    tangent.goov = 2*(state.Rw.*direction.Rwv ...
        +state.Zw.*direction.Zwv);
    tangent.good = zeros(size(state.R));
    tangent.psirv = state.epsilon*state.r./( ...
        state.q.*state.one_minus_sigma_cyl) ...
        .*direction.Tv+zeros(size(state.R));
    tangent.psird = zeros(size(state.R));

    common = state.psir.^2.*state.goo./state.J.^3;
    tangent.Bp2v = 2*state.epsilon^2*( ...
        state.psir.*state.goo./state.J.^2.*tangent.psirv ...
        +0.5*state.psir.^2./state.J.^2.*tangent.goov ...
        -common.*tangent.Jv);
    tangent.Bp2d = -2*state.epsilon^2*common.*tangent.Jd;
end

function condensed = local_B_tangent(state,direction,tangent,local)
    sigma_R = local.pressure.PRB./local.B;
    fixed_B_Gv = -sigma_R.*direction.Rv ...
        -direction.Tv./(state.R.*local.Bphi) ...
        +state.T.*direction.Rv./(state.R.^2.*local.Bphi) ...
        -state.T.*tangent.Bp2v./( ...
            2*state.R.*local.Bphi.^3);
    fixed_B_Gd = -state.T.*tangent.Bp2d./( ...
        2*state.R.*local.Bphi.^3);

    condensed.Bv = -fixed_B_Gv./local.GB;
    condensed.Bd = -fixed_B_Gd./local.GB;
    condensed.Bphiv = (local.B.*condensed.Bv ...
        -0.5*tangent.Bp2v)./local.Bphi;
    condensed.Bphid = (local.B.*condensed.Bd ...
        -0.5*tangent.Bp2d)./local.Bphi;
    condensed.sigmav = sigma_R.*direction.Rv ...
        +local.sigma_B.*condensed.Bv;
    condensed.sigmad = local.sigma_B.*condensed.Bd;
    condensed.Piv = local.pressure.PR.*direction.Rv ...
        +local.pressure.PB.*condensed.Bv;
    condensed.Pid = local.pressure.PB.*condensed.Bd;
    condensed.Prv = local.pressure.PrR.*direction.Rv ...
        +local.pressure.PrB.*condensed.Bv;
    condensed.Prd = local.pressure.PrB.*condensed.Bd;
    condensed.PRv = local.pressure.PRR.*direction.Rv ...
        +local.pressure.PRB.*condensed.Bv;
    condensed.PRd = local.pressure.PRB.*condensed.Bd;
end

function result = flux_derivative_tangent(state,tangent,condensed,local)
    one_minus_sigma = 1-local.sigma;
    prefactor = state.epsilon;
    result.v = prefactor*( ...
        -condensed.sigmav.*state.goo.*state.psir./state.J ...
        +one_minus_sigma.*( ...
            tangent.goov.*state.psir./state.J ...
            +state.goo.*tangent.psirv./state.J ...
            -state.goo.*state.psir.*tangent.Jv./state.J.^2));
    result.d = prefactor*( ...
        -condensed.sigmad.*state.goo.*state.psir./state.J ...
        +one_minus_sigma.*( ...
            -state.goo.*state.psir.*tangent.Jd./state.J.^2));
end

function result = flux_source_tangent(state,direction,condensed,local)
    one_minus_sigma = 1-local.sigma;
    anisotropic_source = state.T.*state.Tr./( ...
        state.R.^2.*one_minus_sigma);
    result.v = condensed.Prv ...
        +state.Tr.*direction.Tv./(state.R.^2.*one_minus_sigma) ...
        -2*anisotropic_source.*direction.Rv./state.R ...
        +anisotropic_source.*condensed.sigmav./one_minus_sigma;
    result.d = condensed.Prd ...
        +state.T.*direction.Tv./(state.R.^2.*one_minus_sigma) ...
        +anisotropic_source.*condensed.sigmad./one_minus_sigma;
end

function [coeff_J,coeff_R,coeff_goo] = ...
        anisotropic_coefficients(state,local)
    Tshift = state.T-state.a0;
    coeff_J = 0.5*state.Bp2-local.pressure.Pi ...
        -state.T.*state.Bp2./(state.R.*local.Bphi) ...
        +0.5*(local.Bphi-state.T./state.R).^2 ...
        -0.5*Tshift.*(state.T+state.a0)./state.R.^2;
    toroidal_R_kernel = state.T.*(state.R.*local.Bphi-state.T) ...
        +Tshift.*(state.T+state.a0);
    coeff_R = state.J.*( ...
        -local.pressure.PR+toroidal_R_kernel./state.R.^3);
    coeff_goo = state.T.*(state.epsilon*state.psir).^2./( ...
        2*state.R.*local.Bphi.*state.J);
end

function [dcoeff_J,dcoeff_R,dcoeff_goo] = coefficient_tangents( ...
        state,direction,tangent,condensed,local)
    vacuum_T2 = state.T.^2-state.a0^2;
    toroidal_difference = local.Bphi-state.T./state.R;

    d_toroidal_difference_v = condensed.Bphiv ...
        -direction.Tv./state.R ...
        +state.T.*direction.Rv./state.R.^2;
    d_toroidal_difference_d = condensed.Bphid;

    d_TBp2_over_RBphi_v = ...
        state.Bp2.*direction.Tv./(state.R.*local.Bphi) ...
        +state.T.*tangent.Bp2v./(state.R.*local.Bphi) ...
        -state.T.*state.Bp2.*direction.Rv./( ...
            state.R.^2.*local.Bphi) ...
        -state.T.*state.Bp2.*condensed.Bphiv./( ...
            state.R.*local.Bphi.^2);
    d_TBp2_over_RBphi_d = ...
        state.T.*tangent.Bp2d./(state.R.*local.Bphi) ...
        -state.T.*state.Bp2.*condensed.Bphid./( ...
            state.R.*local.Bphi.^2);

    dcoeff_J.v = 0.5*tangent.Bp2v-condensed.Piv ...
        -d_TBp2_over_RBphi_v ...
        +toroidal_difference.*d_toroidal_difference_v ...
        -state.T.*direction.Tv./state.R.^2 ...
        +vacuum_T2.*direction.Rv./state.R.^3;
    dcoeff_J.d = 0.5*tangent.Bp2d-condensed.Pid ...
        -d_TBp2_over_RBphi_d ...
        +toroidal_difference.*d_toroidal_difference_d;

    % The vacuum-subtracted toroidal kernel simplifies to
    % T*R*Bphi-a0^2.  Explicit R dependence enters through -P_parallel,R.
    toroidal_R_kernel = state.T.*state.R.*local.Bphi-state.a0^2;
    inner = -local.pressure.PR+toroidal_R_kernel./state.R.^3;
    dkernel_v = direction.Tv.*state.R.*local.Bphi ...
        +state.T.*direction.Rv.*local.Bphi ...
        +state.T.*state.R.*condensed.Bphiv;
    dkernel_d = state.T.*state.R.*condensed.Bphid;
    dinner_v = -condensed.PRv+dkernel_v./state.R.^3 ...
        -3*toroidal_R_kernel.*direction.Rv./state.R.^4;
    dinner_d = -condensed.PRd+dkernel_d./state.R.^3;
    dcoeff_R.v = inner.*tangent.Jv+state.J.*dinner_v;
    dcoeff_R.d = inner.*tangent.Jd+state.J.*dinner_d;

    scale = state.epsilon^2;
    dcoeff_goo.v = scale*( ...
        state.psir.^2.*direction.Tv./( ...
            2*state.R.*local.Bphi.*state.J) ...
        +state.T.*state.psir.*tangent.psirv./( ...
            state.R.*local.Bphi.*state.J) ...
        -state.T.*state.psir.^2.*direction.Rv./( ...
            2*state.R.^2.*local.Bphi.*state.J) ...
        -state.T.*state.psir.^2.*condensed.Bphiv./( ...
            2*state.R.*local.Bphi.^2.*state.J) ...
        -state.T.*state.psir.^2.*tangent.Jv./( ...
            2*state.R.*local.Bphi.*state.J.^2));
    dcoeff_goo.d = scale*( ...
        -state.T.*state.psir.^2.*condensed.Bphid./( ...
            2*state.R.*local.Bphi.^2.*state.J) ...
        -state.T.*state.psir.^2.*tangent.Jd./( ...
            2*state.R.*local.Bphi.*state.J.^2));
end

function result = product_rule(a,db,b,da)
    result.v = a.*db.v+b.*da.v;
    result.d = a.*db.d+b.*da.d;
end

function block = project_linear( ...
        L,test_profile,linear,trial_profile,use_test_derivative)
    average_value = mean(linear.v,2);
    average_derivative = mean(linear.d,2);
    weighted_trials = spdiags(L.w_r.*average_value,0, ...
            length(L.w_r),length(L.w_r))*L.B0{trial_profile} ...
        +spdiags(L.w_r.*average_derivative,0, ...
            length(L.w_r),length(L.w_r))*L.B1{trial_profile};
    if use_test_derivative
        block = L.B1{test_profile}'*weighted_trials;
    else
        block = L.B0{test_profile}'*weighted_trials;
    end
end

function block = project_edge_linear(L,test_profile,linear,trial_profile)
    average_value = mean(linear.v,2);
    average_derivative = mean(linear.d,2);
    trial = average_value*L.B0_edge{trial_profile} ...
        +average_derivative*L.B1_edge{trial_profile};
    block = L.B0_edge{test_profile}'*trial;
end

function rows = block_rows(L,profile)
    first = L.profile_starts(profile);
    rows = first:first+L.profile_lengths(profile)-1;
end
