%% Variational EQUIL proof of principle
% B is eliminated at the two-dimensional quadrature points.  The only
% global profiles are t2, Delta, the SFL gauge P and the S_m harmonics.

[L, LX] = equilVariationalSol( ...
    'beta', 0, ...
    'm', 8, ...
    'nq', 6, ...
    'spline_p', 4, ...
    'om_pts', 64, ...
    'Ns', 3, ...
    'equation_of_state', @isotropic, ...
    'debug', 4 ...
     );

LX.eps_val = 0.3;
LX.Sbc = [-1; 0.3; 0];
LY = equilVariationalY(L, LX);

fprintf('Converged: %d, |R| = %.3e, max|G(B)| = %.3e\n', ...
        LY.isconverged, norm(LY.residual), LY.local_B_residual);

figure;
plot(LY.RR.', LY.ZZ.', 'k-');
axis equal
xlabel('$\hat R$', 'Interpreter', 'latex');
ylabel('$\hat Z$', 'Interpreter', 'latex');
title('Variational EQUIL flux surfaces');
