function LY = equilPP(L, LX, LY)
  % unpack solution vector
  idx = 0;
  t2_c    = LY.x(1:L.dof_count); idx = idx + L.dof_count;
  delta_c = LY.x(idx+1:idx+L.dof_count); idx = idx + L.dof_count;
  P_c     = LY.x(idx+1:idx+L.dof_count); idx = idx + L.dof_count;
  Bs_c    = reshape(LY.x(idx+1:idx+L.P.Nb*L.dof_count), [L.dof_count,1,L.P.Nb]); idx = idx + L.P.Nb*L.dof_count;
  S_unkn  = reshape(LY.x(idx+1:end), [L.dof_count-1,1,L.P.Ns]);

  % build S and B including boundary components
  S_c = cat(1, S_unkn, reshape(LX.Sbc, [1,1,L.P.Ns]));
  Bs_flat = reshape(Bs_c, size(Bs_c,1), []);  % dof_count x Nb  
  S_flat  = reshape(S_c,  size(S_c,1),  []);  % dof_count x Ns

  t2      = L.P0 * t2_c;
  t2p     = L.P1 * t2_c;
  delta   = L.P0 * delta_c;
  deltap  = L.P1 * delta_c;
  deltapp = L.P2 * delta_c;
  P_hat   = L.P0 * P_c;
  Pp      = L.P1 * P_c;
  Ppp     = L.P2 * P_c;

  Bs      = reshape(L.P0 * Bs_flat, L.Nq, 1, []);
  Bsp     = reshape(L.P1 * Bs_flat, L.Nq, 1, []);
  S       = reshape(L.P0 * S_flat, L.Nq, 1, []);
  Sp      = reshape(L.P1 * S_flat, L.Nq, 1, []);
  Spp     = reshape(L.P2 * S_flat, L.Nq, 1, []);
  ms = reshape(linspace(2,L.P.Ns+1,L.P.Ns), [1,1,L.P.Ns]);
  mb = reshape(linspace(0,L.P.Nb-1,L.P.Nb),   [1,1,L.P.Nb]);

  %% bp and li (MEQ conventions)
  RR = 1 - delta.*LX.eps_val.^2 + LX.eps_val.^3.*P_hat.*cos(L.omega) + LX.eps_val.*L.r_q.*cos(L.omega) + LX.eps_val.^2.*sum(cos((-1 + ms).*L.omega).*S,3);
  BB = 1 + LX.eps_val.*sum(Bs.*cos(mb.*L.omega),3);
  [dbetapardB0, ~, dbetapardB, dbetapardR, ~, ...
    ~, ~, ~, ~, ~, ...
    ~, ~, ~, ~, ...
    ~, betapar, betaperp] = L.P.equation_of_state(LX.kinetic_profiles,L.r_q,RR,BB);
  % this is the averaged (p_par + p_perp)/2
  
  Intp = trapz(L.r_q,2*pi*mean(((betapar + betaperp).*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3))))./2.,2));  
  Intpperp = trapz(L.r_q,2*pi*mean((betaperp.*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3))))./2.,2));  
  Intppar = trapz(L.r_q,2*pi*mean((betapar.*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3))))./2.,2));  

  Introt = trapz(L.r_q,2*pi*mean(((dbetapardR.*RR).*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3))))./2.,2));  

  Intphir = 2*pi*mean((L.r_q.*(1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).*((LX.eps_val.^3.*P_hat.*cos(L.omega) + LX.eps_val.*L.r_q.*cos(L.omega) - LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).^2 + (LX.eps_val.^3.*P_hat.*sin(L.omega) + LX.eps_val.*L.r_q.*sin(L.omega) - LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).^2))./(LX.eps_val.^2.*LX.qfun(L.r_q).*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3)))),2);  
  Intphi = Intphir(end);
  Intq = trapz(L.r_q,2*pi*mean((L.r_q.^2.*(1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).^2.*((LX.eps_val.^3.*P_hat.*cos(L.omega) + LX.eps_val.*L.r_q.*cos(L.omega) - LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).^2 + (LX.eps_val.^3.*P_hat.*sin(L.omega) + LX.eps_val.*L.r_q.*sin(L.omega) - LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).^2))./(LX.eps_val.^2.*LX.qfun(L.r_q).^2.*RR.*((LX.eps_val.^2.*P_hat.*cos(L.omega) + L.r_q.*cos(L.omega) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val) + cos(L.omega) + LX.eps_val.^2.*Pp.*cos(L.omega) + LX.eps_val.*sum(cos((-1 + ms).*L.omega).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(L.omega) + L.r_q.*sin(L.omega) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*L.omega)),3)).*(sin(L.omega) + LX.eps_val.^2.*Pp.*sin(L.omega) - LX.eps_val.*sum(sin((-1 + ms).*L.omega).*Sp,3)))),2));
  LY.intp = Intp;
  LY.intphi = Intphi;
  LY.intphir = Intphir;
  LY.intq = Intq;



  % Test better integrals
  JoverR = (LX.eps_val.^3.*P_hat.*cos(L.omega) + ...
LX.eps_val.*L.r_q.*cos(L.omega) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*L.omega).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(L.omega) + LX.eps_val.^3.*Pp.*cos(L.omega) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*L.omega).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(L.omega)) - ...
LX.eps_val.*L.r_q.*sin(L.omega) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*L.omega)),3)).*(LX.eps_val.*sin(L.omega) + ...
LX.eps_val.^3.*Pp.*sin(L.omega) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*L.omega).*Sp,3));
  LY.Wk_test = 2*pi*trapz(L.r_q, 2*pi*mean((betapar + betaperp)/2 .* JoverR .* RR,2));  % to be multiplied by R0^3 * P0
  %LY.Ip_test = trapz(L.r_q, 2*pi*mean(jphi.* JoverR .* RR,2)); % to be multiplied by R0 * B0 /mu0
  LY.bp_liu = 8 * pi * Intp / Intphi^2;

  % rotation, anisotropic ones
  LY.wrot_liu = 8 * pi * Introt / Intphi^2;
  LY.bppar_liu = 8 * pi * Intppar / Intphi^2;
  LY.bpperp_liu = 8 * pi * Intpperp / Intphi^2;
  LY.li_liu = 8 * pi * Intq / Intphi^2; 
  
  LY.gavg = mean((BB.*(1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2))./(BB - dbetapardB.*LX.eps_val.^2),2);
  % augment with r=0 point where required
  % add also at 1
  r_plt = [0; L.r_q; 1];
  delta = [0; delta; delta(end)];
  P_hat = [0; P_hat; P_hat(end)];

  % psiN
  %% ! here missing the anisotropy case!!
  psi = cumtrapz(L.r_q, (1 + LX.eps_val^2 * t2)./LX.q_vec .* L.r_q); % here factor epsilon might be missing
  psiN = (psi - psi(1)) / (psi(end) - psi(1)); % but it does not matter here

  % pad S and Bs with zero at index 0 to match r_plt
  S = cat(1, zeros(1,1,L.P.Ns), S);
  S = cat(1, S, reshape(LX.Sbc, [1,1, L.P.Ns]));
  Bs = cat(1, zeros(1,1,L.P.Nb), Bs);
  Bs = cat(1, Bs, Bs(end,:,:));
  Bsp = cat(1, zeros(1,1,L.P.Nb), Bsp);
  Bsp = cat(1, Bsp, Bsp(end,:,:));

  % Add the first and last points to L.omega
  LY.omega_plt = [L.omega 2*pi];
  BB = 1 + LX.eps_val * sum(Bs .* cos(mb .* LY.omega_plt ), 3);

  % ---- Geometry ----
  RR = 1 + LX.eps_val .* r_plt .* cos(LY.omega_plt ) - LX.eps_val^2 .* delta + ...
    LX.eps_val^2 .* sum(S .* cos((ms-1) .* LY.omega_plt ), 3) + ...
    LX.eps_val^3 .* P_hat .* cos(LY.omega_plt );
  ZZ = LX.eps_val .* r_plt .* sin(LY.omega_plt ) - ...
    LX.eps_val^2 .* sum(S .* sin((ms-1) .* LY.omega_plt ), 3) + ...
    LX.eps_val^3 .* P_hat .* sin(LY.omega_plt );
  % pressures for plotting
    [dbetapardB0, ~, dbetapardB, ~, ~, ...
    ~, ~, ~, ~, ~, ...
    ~, ~, ~, ~, ~, LY.betapar, ...
    LY.betaperp] = L.P.equation_of_state(LX.kinetic_profiles,r_plt,RR,BB);
  % magnetic field components
  t2 = [0; t2; t2(end)];
  Pp = [0; Pp; Pp(end)];
  deltap = [0;deltap; deltap(end)];
  Sp = cat(1, zeros(1,1,L.P.Ns), Sp);
  Sp = cat(1, Sp,  Sp(end,:,:).*ones(1,1,L.P.Ns));
  % not correct, but for jphi on axis
  Spp = cat(1, zeros(1,1,L.P.Ns), Spp); % not strictly correct, but should be fine
  Spp = cat(1, Spp,  Spp(end,:,:).*ones(1,1,L.P.Ns));
  t2p = [t2(2)/(r_plt(2)-r_plt(1)); t2p; t2p(end)];
  deltapp = [deltap(2)/(r_plt(2)-r_plt(1)); deltapp; deltapp(end)];
  Ppp = [Pp(2)/(r_plt(2)-r_plt(1)); Ppp; Ppp(end)];
  LY.BBp2 = (r_plt.^2.*(1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).^2.*...
      ((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
      LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
      (LX.eps_val.^3.*P_hat.*sin(LY.omega_plt) + LX.eps_val.*r_plt.*sin(LY.omega_plt) - ...
      LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).^2))...
      ./(LX.qfun(r_plt).^2.*RR.^2.*((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) - ...
      LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + ...
      LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))).^2);
  LY.BBt2 = (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).^2./(RR - (dbetapardB.*LX.eps_val.^2.*RR)./(1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3))).^2;
  LY.BB2 = ((1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).^2.*(BB.^2./(BB - dbetapardB.*LX.eps_val.^2).^2 + (r_plt.^2.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + (LX.eps_val.^3.*P_hat.*sin(LY.omega_plt) + LX.eps_val.*r_plt.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).^2))./(LX.qfun(r_plt).^2.*((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))).^2)))./RR.^2;


  LY.jphi = RR.*((LX.eps_val.^2.*(1 - dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).^2))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat.*...
cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) - (LX.eps_val.^2.*LX.qpfun(r_plt).*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).^2))./(LX.qfun(r_plt).^2.*RR.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) + ...
(LX.eps_val.^4.*r_plt.*t2p.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).^2))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat.*...
cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) - (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).^2).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3)))./(LX.qfun(r_plt).*RR.^2.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) + (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).*((-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) ...
- LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3))))./(LX.qfun(r_plt).*RR.^2.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) + (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) ...
- LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3))).*((-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(-((-1 + ...
ms).^2.*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*cos(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).^2.*cos((-1 + ms).*LY.omega_plt).*S),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(LX.eps_val.*sin(LY.omega_plt)) - ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*LY.omega_plt).*Sp),3))))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat....
*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3))).^2) - (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((-(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).^2.*cos((-1 + ms).*LY.omega_plt).*S),3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) ...
- LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(LX.eps_val.*cos(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(-((-1 + ...
ms).^2.*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)) + (-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(LX.eps_val.*sin(LY.omega_plt)) - ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*LY.omega_plt).*Sp),3))))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat....
*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) + (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*(2.*(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(LX.eps_val.*cos(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
2.*(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(LX.eps_val.*sin(LY.omega_plt)) - ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*LY.omega_plt).*Sp),3))))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat....
*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)))) - (LX.eps_val.^2.*r_plt.*(1 - ...
dbetapardB0.*LX.eps_val.^2 + ...
LX.eps_val.^2.*t2).*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).^2).*((-(deltap.*LX.eps_val.^2) ...
+ LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3)).*(LX.eps_val.*cos(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*Sp,3)) - (LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)).*(-(LX.eps_val.*sin(LY.omega_plt)) - ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ms).*LY.omega_plt).*Sp),3)) + ...
(LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) ...
- LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltapp.*LX.eps_val.^2) + ...
LX.eps_val.^3.*Ppp.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Spp,3)) - (-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).*(LX.eps_val.^3.*Ppp.*sin(LY.omega_plt) - ...
LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Spp,3))))./(LX.qfun(r_plt).*RR.*((LX.eps_val.^3.*P_hat....
*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3))).^2))./(RR.*((LX.eps_val.^3.*P_hat.*cos(LY.omega_plt)...
 + LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3))));
  % extrema and geometric measures
  [rmin, irmin] = min(RR, [], 2);
  [rmax, irmax] = max(RR, [], 2);
  [zmin, izmin] = min(ZZ, [], 2);
  [zmax, izmax] = max(ZZ, [], 2);

  Nr = numel(r_plt);
  zrmin = ZZ(sub2ind(size(ZZ), (1:Nr).', irmin));
  zrmax = ZZ(sub2ind(size(ZZ), (1:Nr).', irmax));
  rzmin = RR(sub2ind(size(RR), (1:Nr).', izmin));
  rzmax = RR(sub2ind(size(RR), (1:Nr).', izmax));

  kappa = (zmax - zmin) ./ (rmax - rmin);
  rgeom = (rmax + rmin)/2;
  zgeom = (zmax + zmin)/2;
  aminor = (rmax - rmin)/2;
  deltal = (rgeom - rzmin) ./ aminor;
  deltau = (rgeom - rzmax) ./ aminor;
  deltatrig = (deltal + deltau)/2;

  % Add grid area element (dA = R0^2 * JoverR d\hat rd\omega)
  LY.JoverR = (LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + ...
LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val.^2) + ...
LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + ...
LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) - ...
(-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - ...
LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(LX.eps_val.*sin(LY.omega_plt) + ...
LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3));

  % Volume Integrals
  LY.Wk = 2*pi*equil_2D_integral((LY.betapar + LY.betaperp).*ones(size(LY.JoverR))/2, r_plt, LY.omega_plt...
      , LY.JoverR .* RR, true); % to be multiplied by R0^3 * P0
  LY.Wkperp = 2*pi*equil_2D_integral(LY.betaperp.*ones(size(LY.JoverR)), r_plt, LY.omega_plt...
      , LY.JoverR .* RR, true); % to be multiplied by R0^3 * P0
  LY.Wkpar = 2*pi*equil_2D_integral(LY.betapar.*ones(size(LY.JoverR)), r_plt, LY.omega_plt...
      , LY.JoverR .* RR, true); % to be multiplied by R0^3 * P0
  LY.Wp = 2*pi*equil_2D_integral(LY.BBp2, r_plt, LY.omega_plt...
      , LY.JoverR .* RR, false); % to be multiplied by R0^3 * B0^2 /2 /mu0

  
  
  % Surface Integrals
  LY.Ip = equil_2D_integral(LY.jphi, r_plt, LY.omega_plt...
      , LY.JoverR, false); % to be multiplied by R0 * B0 /mu0
  
  LY.Ft =  equil_2D_integral(sqrt(LY.BBt2), r_plt, LY.omega_plt...
      , LY.JoverR, true); % to be multiplied by R0^2 * B0
  LY.Ft0 = equil_2D_integral(1./RR, r_plt, LY.omega_plt...
      , LY.JoverR, true); % to be multiplied by R0^2 * B0

  %% SFL part
  if L.P.do_SFL
  LY.theta_SFL = LX.eps_val^(-2) * cumtrapz(LY.omega_plt, LY.JoverR ./RR,2) ./ r_plt;
  LY.theta_SFL(1,:) = LY.omega_plt;
  [LY.RR_sfl, LY.ZZ_sfl] = regrid_to_SFL(RR, ZZ, LY.theta_SFL, r_plt, LY.omega_plt);

  % compute N = gtt/Jac in SFL coordinates
  goo = (LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).^2 + (-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).^2;
  J_SFL = LX.eps_val * r_plt .* RR .^2; % to be multiplied by R0^2
  dthetaSFLdomega = LY.JoverR ./ RR./ r_plt * LX.eps_val^(-2);
  gtt = (dthetaSFLdomega).^(-2) .* goo; % to be multiplied by R0^2
  LY.N_SFL = gtt./J_SFL; % currently, on the (r,\omega) grid, to be regridded if we want to pass it to VENUS-MHD

  % compute M = grt/Jac in SFL coordinates
  gro = (-(LX.eps_val.^3.*P_hat.*sin(LY.omega_plt)) - LX.eps_val.*r_plt.*sin(LY.omega_plt) + LX.eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(-(deltap.*LX.eps_val.^2) + LX.eps_val.*cos(LY.omega_plt) + LX.eps_val.^3.*Pp.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) - LX.eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(LX.eps_val.*sin(LY.omega_plt) + LX.eps_val.^3.*Pp.*sin(LY.omega_plt) - LX.eps_val.^2.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3));
  dthetaSFLdr = cumtrapz(LY.omega_plt,(RR.*(-((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) - ...
LX.eps_val.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3))) - (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + ...
r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - ...
LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))) - ...
LX.eps_val.*r_plt.*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3)).*((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + ...
r_plt.*cos(LY.omega_plt) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + ...
r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - ...
LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))) + ...
r_plt.*RR.*((-(deltap.*LX.eps_val) + cos(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3)).*(cos(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*cos(LY.omega_plt) - LX.eps_val.*sum((-1 + ms).*cos((-1 ...
+ ms).*LY.omega_plt).*Sp,3)) + (sin(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ...
ms).*LY.omega_plt).*Sp,3)).*(sin(LY.omega_plt) + ...
LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ...
ms).*sin((-1 + ms).*LY.omega_plt).*Sp),3)) + ...
LX.eps_val.*(LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) ...
- LX.eps_val.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3)).*(-deltapp + LX.eps_val.*Ppp.*cos(LY.omega_plt) + ...
sum(cos((-1 + ms).*LY.omega_plt).*Spp,3)) + ...
LX.eps_val.*(LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) ...
- LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)).*(LX.eps_val.*Ppp.*sin(LY.omega_plt) - sum(sin((-1 + ...
ms).*LY.omega_plt).*Spp,3))))./(r_plt.^2.*RR.^2),2);
  grt = dthetaSFLdomega.^(-1) .* (gro - goo .* dthetaSFLdr ./ dthetaSFLdomega);


  LY.M_SFL = grt./J_SFL;
  grr = LX.eps_val.^2.*((-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)).^2 + (sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3)).^2);
  grr_SFL = grr + 2*gro.^2 ./ goo + grt.^2 ./ gtt;
  LY.L_SFL = grr_SFL ./ J_SFL;

  % analytical result, Daniele Eq.(5.25)
  LY.N_ana = LX.eps_val * r_plt .* (1 + 2 * LX.eps_val * deltap .* cos(LY.theta_SFL) + ...
      LX.eps_val^2 * deltap.^2 /2 + (3/4) * LX.eps_val^2 .* r_plt.^2 + LX.eps_val^2 * delta + ...
      (0) .* cos(2*LY.theta_SFL));

  % my analytical estimates
  LY.N_ana2 = LX.eps_val.*r_plt + 2.*LX.eps_val.^2.*r_plt.*(deltap.*cos(LY.omega_plt) - ...
cos(LY.omega_plt).*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3) + ...
sin(LY.omega_plt).*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
(LX.eps_val.^3.*(sin(LY.omega_plt).^2.*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3).^2 + cos(LY.omega_plt).^2.*sum(-((-1 + ms).*S.*sin((-1 ...
+ ms).*LY.omega_plt)),3).^2 - 2.*r_plt.*cos(LY.omega_plt).*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*LY.omega_plt)),3).*(-(deltap.*sin(LY.omega_plt)) + ...
sin(LY.omega_plt).*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3) + ...
cos(LY.omega_plt).*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3)) + ...
2.*sin(LY.omega_plt).*sum((-1 + ms).*cos((-1 + ...
ms).*LY.omega_plt).*S,3).*(-(cos(LY.omega_plt).*sum(-((-1 + ms).*S.*sin((-1 + ...
ms).*LY.omega_plt)),3)) + r_plt.*(-(deltap.*sin(LY.omega_plt)) + ...
sin(LY.omega_plt).*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3) + ...
cos(LY.omega_plt).*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))) + ...
(r_plt.^2.*(3.*deltap.^2 - 4.*Pp + 3.*deltap.^2.*cos(2.*LY.omega_plt) + ...
6.*cos(LY.omega_plt).^2.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3).^2 + ...
6.*deltap.*sin(2.*LY.omega_plt).*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3) + ...
6.*sin(LY.omega_plt).^2.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3).^2 - ...
12.*cos(LY.omega_plt).*sum(cos((-1 + ...
ms).*LY.omega_plt).*Sp,3).*(deltap.*cos(LY.omega_plt) + ...
sin(LY.omega_plt).*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))))./2.))./r_plt;
  end
  % ---- Package results ----
  LY.r_plt = r_plt;
  LY.t2 = t2;
  LY.t2p = t2p;
  LY.delta = delta;
  LY.deltap = deltap;
  LY.deltapp = deltapp;
  LY.P = P_hat;
  LY.Pp = Pp;
  LY.Bs = Bs;
  LY.Bsp = Bsp;
  LY.S = S;
  LY.Sp = Sp;
  LY.Spp = Spp;
  LY.BB = BB;
  LY.psiN = psiN;
  LY.RR = RR;
  LY.ZZ = ZZ;
  LY.kappa = kappa;
  LY.deltatrig = deltatrig;
  LY.aminor = aminor;
end


function [R_sfl, Z_sfl] = regrid_to_SFL(RR, ZZ, theta_SFL, r_plt, omega_plt)
    Nr     = numel(r_plt);
    Ntheta = numel(omega_plt);
    theta_uniform = linspace(0, 2*pi, Ntheta);

    R_sfl = ones(Nr, Ntheta);
    Z_sfl = zeros(Nr, Ntheta);

    for i = 2 : Nr
        th_ext = [theta_SFL(i,end)-2*pi, theta_SFL(i,:), theta_SFL(i,1)+2*pi];
        R_ext  = [RR(i,end),             RR(i,:),        RR(i,1)];
        Z_ext  = [ZZ(i,end),             ZZ(i,:),        ZZ(i,1)];

        [th_ext, idx] = unique(th_ext);
        R_ext = R_ext(idx);
        Z_ext = Z_ext(idx);

        R_sfl(i,:) = interp1(th_ext, R_ext, theta_uniform, 'spline');
        Z_sfl(i,:) = interp1(th_ext, Z_ext, theta_uniform, 'spline');
    end
end