function LY = equilPP(L, LX, LY)
    [t2, t2p, delta, deltap, deltapp, P_hat, Pp, Ppp, Bs, Bsp, S, Sp, Spp] = ...
          equil_unpack_state(LY.x, L.dof_count, L.P.Nb, LX.Sbc, L.P0, L.P1, L.P2);
   ms = reshape(linspace(2,L.P.Ns+1,L.P.Ns), [1,1,L.P.Ns]);
   mb = reshape(linspace(0,L.P.Nb-1,L.P.Nb), [1,1,L.P.Nb]);
  % ── 2. Fields on quadrature grid (L.r_q x L.omega) ────────────────────
  RR_q = 1 - delta.*LX.eps_val.^2 + LX.eps_val.^3.*P_hat.*cos(L.omega) ...
           + LX.eps_val.*L.r_q.*cos(L.omega) ...
           + LX.eps_val.^2.*sum(cos((-1 + ms).*L.omega).*S,3);

  BB_q = 1 + LX.eps_val.*sum(Bs.*cos(mb.*L.omega),3);

  [dbetapardB0, ~, dbetapardB_q, dbetapardR_q, ~, ...
   ~, ~, ~, ~, ~, ~, ~, ~, ~, ~, betapar_q, betaperp_q] = ...
      L.P.equation_of_state(LX.kinetic_profiles, L.r_q, RR_q, BB_q);

  JoverR_q = compute_JoverR(LX.eps_val, L.r_q, L.omega, P_hat, Pp, deltap, S, Sp,ms);
  BBt_q = (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2) ...
         ./ (RR_q - (dbetapardB_q.*LX.eps_val.^2.*RR_q) ...
         ./ (1 + LX.eps_val.*sum(Bs.*cos(mb.*L.omega),3)));
  jphi_q = compute_jphi(LX,L.r_q,L.omega,RR_q,LX.eps_val,dbetapardB0,t2,t2p,deltap,deltapp,P_hat,Pp,Ppp,S,Sp,Spp,ms);
  BBp2_q = compute_BBp2(LX,RR_q,LX.eps_val,L.r_q,L.omega,t2,P_hat, Pp, deltap, S, Sp,ms,dbetapardB0);

  % ── 3. Surface and volume integrals ───────────────────────────────────
  LY.rBt  = (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2*t2(end));
 

  LY.Wk     = 2*pi*trapz(L.r_q, 2*pi*mean((betapar_q + betaperp_q)/2 .* JoverR_q .* RR_q, 2)); % to be multiplied by R0^3 * P0
  LY.Wkpar  = 2*pi*trapz(L.r_q, 2*pi*mean(betapar_q  .* JoverR_q .* RR_q, 2)); % to be multiplied by R0^3 * P0
  LY.Wkperp = 2*pi*trapz(L.r_q, 2*pi*mean(betaperp_q .* JoverR_q .* RR_q, 2)); % to be multiplied by R0^3 * P0
  LY.Wkrot  = 2*pi*trapz(L.r_q, 2*pi*mean(dbetapardR_q .* JoverR_q .* RR_q, 2)); % to be multiplied by R0^3 * P0
  LY.Wp     = 2*pi*trapz(L.r_q, 2*pi*mean(BBp2_q     .* JoverR_q .* RR_q, 2)); % to be multiplied by R0^3 * B0^2 /2 /mu0
  LY.Ip     = trapz(L.r_q, 2*pi*mean(jphi_q  .* JoverR_q,        2)); % to be multiplied by R0 * B0 /mu0
  LY.Ftt    = trapz(L.r_q, 2*pi*mean(BBt_q   .* JoverR_q,        2)); % to be multiplied by R0^2 * B0
  LY.Ft0    = trapz(L.r_q, 2*pi*mean(1./RR_q .* JoverR_q,        2)); % to be multiplied by R0^2 * B0
  LY.Ft     = LY.Ftt - LY.rBt * LY.Ft0;   % to be multiplied by R0^2 * B0

  LY.bp = LY.Wk / LY.Ip^2 * LX.eps_val^2 * 4;
  LY.bppar = LY.Wkpar / LY.Ip^2 * LX.eps_val^2 * 4 /2; % factor 1/2 to get back bp
  LY.bpperp = LY.Wkperp / LY.Ip^2 * LX.eps_val^2 * 4 /2; % factor 1/2 to get back bp
  LY.bprot = LY.Wkrot / LY.Ip^2 * LX.eps_val^2 * 4 / 3; % fact 1/3 so that delta(end) = bpli2 + C
  LY.li = 2 * LY.Wp / LY.Ip^2;
  LY.bpli2 = (LY.bppar + LY.bpperp + LY.bprot) + LY.li/2;

  % might be wrong, especially with dummy B residuals
  LY.gavg   = mean((BB_q.*(1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2)) ...
                  ./(BB_q - dbetapardB_q.*LX.eps_val.^2), 2);

  % ── psiN ──────────────────────────────────────────────────────────────
  psi       = cumtrapz(L.r_q, (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val^2 .* t2)./LX.qfun(L.r_q) .* L.r_q);
  LY.psiN_q   = (psi - psi(1)) / (psi(end) - psi(1));

  % ── 4. Plotting grid and geometry  ───────────
  LY = equilPP_to_plot_grid(L, LX, LY, t2, t2p, delta, deltap, deltapp, ...
                  P_hat, Pp, Ppp, S, Sp, Spp, Bs, Bsp, Ppp);

end


function LY = equilPP_to_plot_grid(L, LX, LY, t2, t2p, delta, deltap, deltapp, ...
                          P_hat, Pp, Ppp, S, Sp, Spp, Bs, Bsp, ~)
  % Recomputes all fields on the extended plotting grid:
  %   r_plt   = [0; L.r_q; 1]
  %   omega_plt = [L.omega, 2*pi]   (closed contour for plotting)

  r_plt         = [0; L.r_q; 1];
  LY.omega_plt  = [L.omega 2*pi];
  LY.r_plt      = r_plt;

  % Pad profiles to r_plt size
  delta   = [0;      delta;   delta(end)];
  P_hat   = [0;      P_hat;   P_hat(end)];
  t2      = [0;      t2;      t2(end)];
  Pp      = [0;      Pp;      Pp(end)];
  deltap  = [0;      deltap;  deltap(end)];
  t2p     = [t2(2)/(r_plt(2)-r_plt(1));  t2p;      t2p(end)];
  deltapp = [deltap(2)/(r_plt(2)-r_plt(1)); deltapp; deltapp(end)];
  Ppp     = [Pp(2)/(r_plt(2)-r_plt(1));  Ppp;      Ppp(end)];

  S   = cat(1, zeros(1,1,L.P.Ns), S,   reshape(LX.Sbc,        [1,1,L.P.Ns]));
  Sp  = cat(1, zeros(1,1,L.P.Ns), Sp,  Sp(end,:,:) .*ones(1,1,L.P.Ns));
  Spp = cat(1, zeros(1,1,L.P.Ns), Spp, Spp(end,:,:).*ones(1,1,L.P.Ns));
  Bs  = cat(1, zeros(1,1,L.P.Nb), Bs,  Bs(end,:,:));
  Bsp = cat(1, zeros(1,1,L.P.Nb), Bsp, Bsp(end,:,:));

  % ── Geometry ──────────────────────────────────────────────────────────
  LY.BB  = 1 + LX.eps_val .* sum(Bs .* cos(reshape(linspace(0,L.P.Nb-1,L.P.Nb),[1,1,L.P.Nb]) .* LY.omega_plt), 3);
  LY.RR  = 1 + LX.eps_val .* r_plt .* cos(LY.omega_plt) ...
             - LX.eps_val^2 .* delta ...
             + LX.eps_val^2 .* sum(S .* cos((reshape(linspace(2,L.P.Ns+1,L.P.Ns),[1,1,L.P.Ns])-1) .* LY.omega_plt), 3) ...
             + LX.eps_val^3 .* P_hat .* cos(LY.omega_plt);
  LY.ZZ  = LX.eps_val .* r_plt .* sin(LY.omega_plt) ...
             - LX.eps_val^2 .* sum(S .* sin((reshape(linspace(2,L.P.Ns+1,L.P.Ns),[1,1,L.P.Ns])-1) .* LY.omega_plt), 3) ...
             + LX.eps_val^3 .* P_hat .* sin(LY.omega_plt);
  RR = LY.RR; ZZ = LY.ZZ;
  [dbetapardB0, ~, dbetapardB, ~, d2betapardB2, d2betapardrdB, d2betapardRdB, ~, ~, ~, ~, ~, ~, ~, ~, LY.betapar, LY.betaperp] = ...
      L.P.equation_of_state(LX.kinetic_profiles, r_plt, LY.RR, LY.BB);
  LY.dbetapardB0 = dbetapardB0;
  LY.t2      = t2;    LY.t2p  = t2p;
  LY.delta   = delta; LY.deltap = deltap; LY.deltapp = deltapp;
  LY.P       = P_hat; LY.Pp   = Pp;       LY.Ppp = Ppp;
  LY.Bs      = Bs;    LY.Bsp  = Bsp;
  LY.S       = S;     LY.Sp   = Sp;       LY.Spp = Spp;

  % ── Magnetic field components on plotting grid ────────────────────────
  ms  = reshape(linspace(2,L.P.Ns+1,L.P.Ns), [1,1,L.P.Ns]);
  mb  = reshape(linspace(0,L.P.Nb-1,L.P.Nb), [1,1,L.P.Nb]);

  LY.JoverR = compute_JoverR(LX.eps_val, r_plt, LY.omega_plt, P_hat, Pp, deltap, S, Sp,ms);  
  LY.BBp2   = compute_BBp2(LX,RR,LX.eps_val,r_plt,LY.omega_plt,t2,P_hat, Pp, deltap, S, Sp,ms,dbetapardB0);
  LY.BBt2   = (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).^2 ...
              ./ (LY.RR - (dbetapardB.*LX.eps_val.^2.*LY.RR)./(1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3))).^2;
  LY.BB2    = LY.BBt2 + LY.BBp2;
  if func2str(L.P.residuals_fun) == "residuals_iso_static"
      LY.BB = sqrt(LY.BB2); % catch case of dummy residuals
  end
  LY.jphi   = compute_jphi(LX,r_plt,LY.omega_plt,RR,LX.eps_val,dbetapardB0,t2,t2p,deltap,deltapp,P_hat,Pp,Ppp,S,Sp,Spp,ms);

  % ── psiN ──────────────────────────────────────────────────────────────
  psi       = cumtrapz(r_plt, (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val^2 .* t2)./LX.qfun(r_plt) .* r_plt);
  LY.psi    = psi;
  LY.psiN   = (psi - psi(1)) / (psi(end) - psi(1));
  LY.T = (1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val^2 .* t2);

  % ── rhotor ────────────────────────────────────────────────────────────
  toroidal_flux = 2*pi*mean(sqrt(LY.BBt2) .* LY.JoverR, 2);
  LY.rhotor     = sqrt(toroidal_flux / toroidal_flux(end));

  % ── Shape/geometry ────────────────────────────────────────────────────
  [rmin, irmin] = min(LY.RR, [], 2);  [rmax, irmax] = max(LY.RR, [], 2);
  [zmin, izmin] = min(LY.ZZ, [], 2);  [zmax, izmax] = max(LY.ZZ, [], 2);
  Nr = numel(r_plt);
  zrmin = LY.ZZ(sub2ind(size(LY.ZZ), (1:Nr).', irmin));
  zrmax = LY.ZZ(sub2ind(size(LY.ZZ), (1:Nr).', irmax));
  rzmin = LY.RR(sub2ind(size(LY.RR), (1:Nr).', izmin));
  rzmax = LY.RR(sub2ind(size(LY.RR), (1:Nr).', izmax));

  LY.kappa     = (zmax - zmin) ./ (rmax - rmin);
  LY.rgeom     = (rmax + rmin)/2;
  LY.zgeom     = (zmax + zmin)/2;
  LY.aminor    = (rmax - rmin)/2;
  LY.deltal    = (LY.rgeom - rzmin) ./ LY.aminor;
  LY.deltau    = (LY.rgeom - rzmax) ./ LY.aminor;
  LY.deltatrig = (LY.deltal + LY.deltau)/2;

  % ── SFL ───────────────────────────────────────────────────
  if L.P.do_SFL
    % contravariant components of the current
    LY.Jupr = -(((1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).*(dbetapardB.*LX.eps_val.*sum(-(mb.*Bs.*sin(mb.*LY.omega_plt)),3) - (1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3)).*(d2betapardB2.*LX.eps_val.*sum(-(mb.*Bs.*sin(mb.*LY.omega_plt)),3) - d2betapardRdB.*LX.eps_val.*(LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)))))./((1 - dbetapardB.*LX.eps_val.^2 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3)).^2.*(1 - delta.*LX.eps_val.^2 + LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*S,3)).*((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3)))));
    LY.Jupomega = (-(t2p.*(1 - (dbetapardB.*LX.eps_val.^2)./(1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3)))) + ((1 - dbetapardB0.*LX.eps_val.^2 + LX.eps_val.^2.*t2).*(dbetapardB.*LX.eps_val.*sum(Bsp.*cos(mb.*LY.omega_plt),3) - (1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3)).*(d2betapardrdB + d2betapardB2.*LX.eps_val.*sum(Bsp.*cos(mb.*LY.omega_plt),3) + d2betapardRdB.*LX.eps_val.*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)))))./(1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3)).^2)./((-1 + (dbetapardB.*LX.eps_val.^2)./(1 + LX.eps_val.*sum(Bs.*cos(mb.*LY.omega_plt),3))).^2.*(1 - delta.*LX.eps_val.^2 + LX.eps_val.^3.*P_hat.*cos(LY.omega_plt) + LX.eps_val.*r_plt.*cos(LY.omega_plt) + LX.eps_val.^2.*sum(cos((-1 + ms).*LY.omega_plt).*S,3)).*((LX.eps_val.^2.*P_hat.*cos(LY.omega_plt) + r_plt.*cos(LY.omega_plt) - LX.eps_val.*sum((-1 + ms).*cos((-1 + ms).*LY.omega_plt).*S,3)).*(-(deltap.*LX.eps_val) + cos(LY.omega_plt) + LX.eps_val.^2.*Pp.*cos(LY.omega_plt) + LX.eps_val.*sum(cos((-1 + ms).*LY.omega_plt).*Sp,3)) + (LX.eps_val.^2.*P_hat.*sin(LY.omega_plt) + r_plt.*sin(LY.omega_plt) - LX.eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*LY.omega_plt)),3)).*(sin(LY.omega_plt) + LX.eps_val.^2.*Pp.*sin(LY.omega_plt) - LX.eps_val.*sum(sin((-1 + ms).*LY.omega_plt).*Sp,3))));
    LY.Jupphi = LY.jphi ./ RR;
    LY = equil_SFL(L, LX, LY, r_plt, RR, ZZ, delta, deltap, deltapp, P_hat, Pp, Ppp, S, Sp, Spp, ms);
  end
end

function jphi = compute_jphi(LX,r,omega,RR,eps_val, dbetapardB0,t2,t2p,deltap,deltapp,P_hat,Pp,Ppp,S,Sp,Spp,ms)
    jphi = RR.*((eps_val.^2.*(1 - dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).^2 + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*omega)),3)).^2))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat.*...
cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) - (eps_val.^2.*LX.qpfun(r).*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).^2 + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*omega)),3)).^2))./(LX.qfun(r).^2.*RR.*((eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) + ...
(eps_val.^4.*r.*t2p.*((eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).^2 + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*omega)),3)).^2))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat.*...
cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) - (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).^2 + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).^2).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ...
ms).*omega).*Sp,3)))./(LX.qfun(r).*RR.^2.*((eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) + (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*omega)),3)).*((-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) + ...
(eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) ...
- eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3))))./(LX.qfun(r).*RR.^2.*((eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) + (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) + ...
(eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) ...
- eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3))).*((-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) - eps_val.^2.*sum(-((-1 + ...
ms).^2.*S.*sin((-1 + ms).*omega)),3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*cos(omega) + ...
eps_val.^3.*Pp.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*cos(omega)) - ...
eps_val.*r.*cos(omega) + eps_val.^2.*sum(-((-1 + ...
ms).^2.*cos((-1 + ms).*omega).*S),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)) + (eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).*(-(eps_val.*sin(omega)) - ...
eps_val.^3.*Pp.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*omega).*Sp),3))))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat....
*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3))).^2) - (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((-(eps_val.^3.*P_hat.*cos(omega)) - ...
eps_val.*r.*cos(omega) + eps_val.^2.*sum(-((-1 + ...
ms).^2.*cos((-1 + ms).*omega).*S),3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) + ...
(eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) ...
- eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(eps_val.*cos(omega) + ...
eps_val.^3.*Pp.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*Sp,3)) + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) - eps_val.^2.*sum(-((-1 + ...
ms).^2.*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)) + (-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(-(eps_val.*sin(omega)) - ...
eps_val.^3.*Pp.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*omega).*Sp),3))))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat....
*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) + (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*(2.*(eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).*(eps_val.*cos(omega) + ...
eps_val.^3.*Pp.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*Sp,3)) + ...
2.*(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(-(eps_val.*sin(omega)) - ...
eps_val.^3.*Pp.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ...
ms).*omega).*Sp),3))))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat....
*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)))) - (eps_val.^2.*r.*(1 - ...
dbetapardB0.*eps_val.^2 + ...
eps_val.^2.*t2).*((eps_val.^3.*P_hat.*cos(omega) + ...
eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).^2 + ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).^2).*((-(deltap.*eps_val.^2) ...
+ eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ...
ms).*omega).*Sp,3)).*(eps_val.*cos(omega) + ...
eps_val.^3.*Pp.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*Sp,3)) - (eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3)).*(-(eps_val.*sin(omega)) - ...
eps_val.^3.*Pp.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*sin((-1 + ms).*omega).*Sp),3)) + ...
(eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) ...
- eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltapp.*eps_val.^2) + ...
eps_val.^3.*Ppp.*cos(omega) + eps_val.^2.*sum(cos((-1 + ...
ms).*omega).*Spp,3)) - (-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ...
ms).*omega)),3)).*(eps_val.^3.*Ppp.*sin(omega) - ...
eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Spp,3))))./(LX.qfun(r).*RR.*((eps_val.^3.*P_hat....
*cos(omega) + eps_val.*r.*cos(omega) - ...
eps_val.^2.*sum((-1 + ms).*cos((-1 + ...
ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3))).^2))./(RR.*((eps_val.^3.*P_hat.*cos(omega)...
 + eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ...
ms).*cos((-1 + ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + ...
eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + ...
eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - ...
(-(eps_val.^3.*P_hat.*sin(omega)) - ...
eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ...
ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + ...
eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ...
ms).*omega).*Sp,3))));
end

function JoverR = compute_JoverR(eps_val, r, omega, P_hat, Pp, deltap, S, Sp,ms)
    JoverR = (eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*omega).*S,3)).*(-(deltap.*eps_val.^2) + eps_val.*cos(omega) + eps_val.^3.*Pp.*cos(omega) + eps_val.^2.*sum(cos((-1 + ms).*omega).*Sp,3)) - (-(eps_val.^3.*P_hat.*sin(omega)) - eps_val.*r.*sin(omega) + eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*omega)),3)).*(eps_val.*sin(omega) + eps_val.^3.*Pp.*sin(omega) - eps_val.^2.*sum(sin((-1 + ms).*omega).*Sp,3));
end

function BBp2 = compute_BBp2(LX,RR,eps_val,r,omega,t2,P_hat, Pp, deltap, S, Sp,ms,dbetapardB0)
    BBp2 = (r.^2.*(1 - dbetapardB0.*eps_val.^2 + eps_val.^2.*t2).^2.*((eps_val.^3.*P_hat.*cos(omega) + eps_val.*r.*cos(omega) - eps_val.^2.*sum((-1 + ms).*cos((-1 + ms).*omega).*S,3)).^2 + (eps_val.^3.*P_hat.*sin(omega) + eps_val.*r.*sin(omega) - eps_val.^2.*sum(-((-1 + ms).*S.*sin((-1 + ms).*omega)),3)).^2))./(LX.qfun(r).^2.*RR.^2.*((eps_val.^2.*P_hat.*cos(omega) + r.*cos(omega) - eps_val.*sum((-1 + ms).*cos((-1 + ms).*omega).*S,3)).*(-(deltap.*eps_val) + cos(omega) + eps_val.^2.*Pp.*cos(omega) + eps_val.*sum(cos((-1 + ms).*omega).*Sp,3)) + (eps_val.^2.*P_hat.*sin(omega) + r.*sin(omega) - eps_val.*sum(-((-1 + ms).*S.*sin((-1 + ms).*omega)),3)).*(sin(omega) + eps_val.^2.*Pp.*sin(omega) - eps_val.*sum(sin((-1 + ms).*omega).*Sp,3))).^2);
end