function LX = equilVariationalX(L)
%EQUILVARIATIONALX Normalized profiles and fixed-boundary data.
%   Sbc and Abc contain the cosine and sine-quadrature
%   normalized outer shaping values, respectively. Zbc is the optional
%   fixed vertical-center displacement.

    LX.eps_val = 0.3;
    LX.Sbc = zeros(L.P.Ns, 1);
    LX.Sbc(1) = -1;
    if L.P.Ns > 1
        LX.Sbc(2) = 0.3;
    end
    LX.Abc = zeros(L.P.Na, 1);
    LX.Zbc = 0;

    LX.qfun = @(r) L.P.q0 * (1 + 0.5*L.P.s0*r.^2);
    LX.qpfun = @(r) L.P.q0 * L.P.s0*r;

    LX.beta_shape = @(r) 1-r.^2;
    LX.betap_shape = @(r) -2*r;
    beta = @(r) L.P.beta*LX.beta_shape(r);
    betap = @(r) L.P.beta*LX.betap_shape(r);
    LX.beta_value = L.P.beta;
    switch func2str(L.P.equation_of_state)
        case 'isotropic'
            LX.kinetic_profiles = struct('beta', beta, 'betap', betap);
        case 'isotropic_rotating'
            LX.kinetic_profiles = struct( ...
                'beta', beta, 'betap', betap, ...
                'mach2', @(r) L.P.mach20 + zeros(size(r)), ...
                'mach2p', @(r) zeros(size(r)));
        case 'parallel_rotating'
            LX.kinetic_profiles = struct( ...
                'beta', beta, 'betap', betap, ...
                'mach2', @(r) L.P.mach20 + zeros(size(r)), ...
                'mach2p', @(r) zeros(size(r)));
        case 'biMaxwellian'
            LX.kinetic_profiles = struct( ...
                'beta', beta, 'betap', betap, ...
                'Ah', @(r) L.P.A0 + zeros(size(r)), ...
                'Ahp', @(r) zeros(size(r)), ...
                'Bc', @(r) L.P.Bc0 + zeros(size(r)), ...
                'Bcp', @(r) zeros(size(r)));
        case 'de_Blank'
            LX.kinetic_profiles = struct( ...
                'beta', beta, 'betap', betap, ...
                'mach2', @(r) L.P.mach20+zeros(size(r)), ...
                'mach2p', @(r) zeros(size(r)), ...
                'Theta', @(r) L.P.Theta0+zeros(size(r)), ...
                'Thetap', @(r) zeros(size(r)));
        case 'runaways'
            LX.kinetic_profiles = struct( ...
                'beta', beta, 'betap', betap, ...
                'gamma', @(r) L.P.gamma0*(1-r.^2), ...
                'gammap', @(r) -2*L.P.gamma0*r);
        otherwise
            error('The variational pressure adapter does not support %s.', ...
                  func2str(L.P.equation_of_state));
    end

    % Optional native pressure map.  When supplied, it must return a struct
    % with Pi, Pr, PR, PB and PBB for normalized Pi_parallel(r,R,B).
    LX.pressure_map = [];
end
